line-length = 100

[lint]
exclude = [
  ".eggs/*",
  ".tox/*",
  "build/*",
  "docs/*",
  "notebooks/*",
]
select = [
  "C4",  # flake8-comprehensions
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F",  # Pyflakes
]
extend-select = [
  "COM",  # flake8-commas
]
ignore = [
  # pycodestyle (E, W)
  "E501",  # line-too-long
  "E711",  # NoneComparison  (see unfixable)
  "E721",  # type-comparison
  "E731",  # lambda-assignment
  "E741",  # AmbiguousVariableName. Physics variables are often poor code variables

  # flake8-commas (COM)
  "COM812",  # TrailingCommaMissing
  "COM819",  # TrailingCommaProhibited
]
unfixable = ["E711"]

[lint.extend-per-file-ignores]
"*/utils/jwst_utils.py" = [
  "PLC0415"  # `import` should be at the top-level of a file
]
".pyinstaller/*.py" = ["INP001"]
"conftest.py" = ["INP001"]  # Not a package.
"docs/*.py" = [
  "INP001",  # implicit-namespace-package. The examples are not a package.
  "PLC0415",  # `import` should be at the top-level of a file
]  # Part of configuration, not a package.
"examples/*.py" = [
  "E402",  # Imports are done as needed.
  "INP001",  # implicit-namespace-package. The examples are not a package.
  "T203"  # pprint found
]
"setup.py" = [
  "ICN001",
  "INP001",  # Part of configuration, not a package.
  "UP018"
]
"test_*.py" = [
  "B011",
  "B018",  # UselessExpression
  "D",  # pydocstyle
  "D104",
  "F841",  # Local variable `im4_tpwcs` is assigned to but never used
  # "PGH001",  # No builtin eval() allowed
  "PLC0415",
  "S101",  # Use of assert detected
  "SLF001",
]
"test_wcsimage.py" = [
  "RUF015",  # Prefer next({iterable}) over single element slice
]

[lint.flake8-annotations]
ignore-fully-untyped = true
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-type-checking]
exempt-modules = []

[lint.isort]
known-first-party = ["astropy", "extension_helpers"]

[lint.pydocstyle]
convention = "numpy"
