jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: windows-2019
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: macOS-10.15
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: ubuntu-18.04

  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
    maxParallel: 4

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - bash: |
        export PIP_INSTALL='pip install --upgrade'
        echo "##vso[task.setvariable variable=PIP_INSTALL]$PIP_INSTALL"
      condition: ne( variables['Agent.OS'], 'Windows_NT' )
      displayName: Pip on Linux/Darwin

    - powershell: |
        Set-Variable -Name PIP_INSTALL -Value 'python -m pip install --upgrade'
        Write-Host "##vso[task.setvariable variable=PIP_INSTALL]$PIP_INSTALL"
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      displayName: Pip on Windows

    - script: |
        $(PIP_INSTALL) -e .[test]
      displayName: build package

    - script: |
        python -m pip freeze
      displayName: freeze output

    - script: |
        pytest --cov=./ -v --junitxml=junit/test-results.xml
      displayName: run test

    - bash: |
        codecov -t $codecov_token
      env:
        codecov_token: $(CODECOV_TOKEN)
      condition: ne( variables['Agent.OS'], 'Windows_NT' )
      displayName: codecov upload on Linux/Darwin

    - powershell: |
        codecov -t "$(CODECOV_TOKEN)"
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      displayName: codecov upload on Windows

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Python $(python.version)-${{ format(parameters.name) }}'

